### ISSUE TITLE
Tutorial Doubt

### ISSUE THREAD

**Issue by Clasherzz** [HarshAndroid/ApnaChat-Realtime-Chat-App-In-Flutter-Firebase#18]
I am actually going through your tutorial and is kinda at themiddle. While refereing to the github i found out that in home page when you click a button you go to profile screen. Usually in apps you should first check whether user is registered(like whether he is already signed in) and if not he is directed to login. Is this done here in some way. If not can i add it?

**Comment by HarshAndroid** [comment]
Actually we're checking if user is registered or not in splash screen (inside initState), and then navigating according to home screen or login screen.

So if user is navigated to home screen, that means it's registered. That is the reason I'm directly sending it to profile screen on button tap.

**Comment by Clasherzz** [comment]
ohh thanks Sir i get it now.
