### ISSUE TITLE
Blank screen on selecting a chat when on-screen keyboard is displayed

### ISSUE THREAD

**Issue by yoAlienX** [HarshAndroid/ApnaChat-Realtime-Chat-App-In-Flutter-Firebase#21]
### I have found two bugs while using the app. 
1. Blank screen on selecting a chat when keyboard is displayed.
2. Edit option is not working i n any chat.

Refer this image for reference : 

![Screenshot_20241214_203446](https://github.com/user-attachments/assets/dd34ebfd-e46b-434d-9741-d518cd314e54)

**Comment by HarshAndroid** [comment]
Now you can test latest apk and let me know.
