### ISSUE TITLE
Change project name

### ISSUE THREAD

**Issue by Daniel-Khodabakhsh** [HarshAndroid/ApnaChat-Realtime-Chat-App-In-Flutter-Firebase#5]
Nice work on the project!

However.. seriously? WeChat? You know there is an existing application called [WeChat](https://www.wechat.com/) named in 2012 [with over 1.3 BILLION users](https://www.statista.com/statistics/255778/number-of-active-wechat-messenger-accounts/) right??

This is like if you named your project 'WhatsApp' or 'Telegram'. It's confusing.

**Comment by HarshAndroid** [comment]
Actually at the time of creation, I didn't knew that about global WeChat app.

Can you suggest me some good names, so I can change it.

**Comment by rudramistry001** [comment]
Sir u can name this as ApnaChat as it also looks a bit Indian style....

**Comment by HarshAndroid** [comment]
Sounds Good! Done.
